---
resources:
- name: source
  type: git
  source:
    uri: {{bosh2-docker-git-repo}}
    branch: master

- name: bosh2-cli
  type: github-release
  check_every: 12h
  source:
    owner: cloudfoundry
    repository: bosh-cli

- name: credhub-cli
  type: github-release
  check_every: 12h
  source:
    owner: cloudfoundry-incubator
    repository: credhub-cli

- name: docker-registry
  type: docker-image
  source:
    repository: {{bosh2-docker-repository}}
    username: {{docker-registry-username}}
    password: {{docker-registry-password}}
    insecure_registries: [ {{insecure-docker-registries}} ]

jobs:
- name: build-docker-image
  public: true
  plan:
  - aggregate:
    - get: source
      trigger: true
    - get: bosh2-cli
      trigger: true
    - get: credhub-cli
      trigger: true
  - task: get-cli-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          insecure_registries: [ {{insecure-docker-registries}} ]
          repository: {{alpine_image}}
      inputs:
      - name: source
      - name: bosh2-cli
      - name: credhub-cli
      outputs:
      - name: bosh-cli-version
      run:
        path: source/tasks/get-cli-version.sh
  - put: docker-registry
    params:
      build: source
      build_args_file: bosh-cli-version/version.json
